import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className=" bg-gray-800">
        <main className=" flex h-screen flex-col bg-gray-800">
          <div className="flex h-36 w-full items-center justify-center gap-8 border-b-4 border-black bg-gray-800">
            <a href="#">Home</a>
            <a href="#">Projetos</a>
            <a href="#">Sobre</a>
          </div>
          <div className="flex h-full w-full items-start justify-center rounded-xl pt-6">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
